### ISSUE TITLE
Write documentation for Project Boards

### ISSUE THREAD

**Issue by lukas-h** [scalabs/documentation#1]

**Comment by armantorkzaban** [comment]
Project boards are there to help organise and track the tasks. They normally consist of a section called:
- Backlog which lists all the things that have to be done, 
- a section to mark what is inProgress, 
- one section for the tasks that are inReview and finally 
- one for the Done task.
A task that is 'assigned' moves automatically to the inProgress. Once a PR connected to the task/issue is requested, the tasks moves from inProgress to the inReview. Once review is done, conversations are resolved and PR is merged, the task is moved to the pane: Done.
These routines can be controlled in the workflow section.

One noteworthy pane is New. In New we can add things that are not yet a fully engineered feature/issue/task.

**Comment by armantorkzaban** [comment]
Project boards are there to help organise and track the tasks. They normally consist of a section called:
- Backlog which lists all the things that have to be done, 
- a section to mark what is inProgress, 
- one section for the tasks that are inReview and finally 
- one for the Done task.
A task that is 'assigned' moves automatically to the inProgress. Once a PR connected to the task/issue is requested, the tasks moves from inProgress to the inReview. Once review is done, conversations are resolved and PR is merged, the task is moved to the pane: Done.
These routines can be controlled in the workflow section.

One noteworthy pane is New. In New we can add things that are not yet a fully engineered feature/issue/task.

**Comment by lukas-h** [comment]
- [x] describe the different columns "New", "Backlog", "Ready" (to work on), "In Progress", "In Review", "Done" to avoid confusion!!!

**Comment by armantorkzaban** [comment]
- `New` lists all the new objects that are not fully engineered
- `Backlog` lists all the things that have to be done
- `Ready` is a task prepared to be assigned and worked on (moved to In Progress)
- `In Progress` lists all the tasks being actively worked on
- `In Review` lists the tasks that are assigned for review
- `Done` holds all the tasks that are fully done.

@lukas-h in that order?

**Comment by lukas-h** [comment]
Yes, wonderful!
