### ISSUE TITLE
New guide on project documentation, feature engineering

### ISSUE THREAD

**Issue by lukas-h** [scalabs/documentation#12]
**Type of Issue**  
- [x] New Feature Implementation

**Type of Work**  
- [x] Documentation

**Description**  

- [ ] Document how we use our issue templates (feature request, question, bug report) and all of its sections
- [x] Document acceptance criteria

**Comment by lukas-h** [comment]
@armantorkzaban this will be part of next week's session.

**Comment by lukas-h** [comment]
@armantorkzaban Some of the sections are not yet finished:

https://github.com/scalabs/documentation/blob/main/guides/project-documentation.md#create-a-feature-request

**Comment by armantorkzaban** [comment]
@lukas-h check the updated version please.

**Comment by lukas-h** [comment]
Thanks, cool! I also added a few lines. Going to close this issue here
