### ISSUE TITLE
New guide for Debugging

### ISSUE THREAD

**Issue by lukas-h** [scalabs/documentation#4]
- when you are stuck, take the time to document the issue after you have unsuccessfully worked on it for some [time unit]
- Another person can see the problem and has already experienced it
- Transparency
- It's not about skills or not living up to the standards, but time Transparency. Delays are normal, but if they are not communicated, they upset people
- Helps to plan future iterations/sprints realistically
- Don't be afraid to open a "stupid sounding" issue. Stupid mistakes are normal and you learn from them

**Comment by lukas-h** [comment]
Where to document it? Issue, PR, new bug issue

**Comment by lukas-h** [comment]
Not so strong guidelines about this

Issue: conceptual
PR: technical, implementation
New issue: Severe bug

**Comment by armantorkzaban** [comment]
> Where to document it? Issue, PR, new bug issue

Readme > Miscellaneous
