### ISSUE TITLE
clearer versioning convention. 

### ISSUE THREAD

**Issue by armantorkzaban** [scalabs/documentation#5]
What do we call a 

- pre-release, release, build
- etc. (how do we signal bugfixes, what keywords do we use?)

**Comment by lukas-h** [comment]
–> no need to clarify more. We are just following semver.org

**Comment by lukas-h** [comment]
Maybe we could mention just that in the README, that would be good!

**Comment by armantorkzaban** [comment]
What would be a prerelease for us? what do we write when there is a bugfix: 1.0.0-bugfix, 1.0.0+bugfix, 1.0.0.5+fixedXbug?

**Comment by lukas-h** [comment]
No, a pre-release would be -alpha, -beta.

Bug-fix releases could be 0.0.HERE, wdyt?

**Comment by lukas-h** [comment]
Now in retrospective, I'm glad, we have this discussion!

**Comment by armantorkzaban** [comment]
Added to readme in #11
